class HSPricing
{
	class ChainSaw {price = 125;};
	class CircuitParts {price = 50;};
	class ItemCoolerE {price = 50;};
	class JackKit {price = 25;};
	class ItemLockbox {price = 250; tax = 0.5;};
	class ItemSafe {price = 500;};
	class ItemCompass {price = 3;};
	class ItemGPS {price = 20;};
	class EngineBlock {price = 75;};
	class EngineParts {price = 50;};
	class ItemDuctTape {price = 15;};
	class SpareTire	{price = 10;};
	class ItemRotor {price = 50;};
	class ItemGlass {price = 5;};
	class FuelTank {price = 10;};
	class ItemBattery {price = 15;};
	class ItemPipe {price = 10;};
	class ItemCables {price = 10;};
	class ItemSolar {price = 25;};
	class KitSolarGen {price = 100;};
	class ItemBulb {price = 25;};
	class ItemWaterPurificationTablets {price = 50;};
	class ItemEmptyTin {price = 5;};
	class ItemBurlap {price = 10;};
	class KitFuelPump {price = 1500;};
	class KitWatchTower {price = 2500;};
	class KitScaffolding {price = 1500;};
	class ItemCanvas {price = 150;};
	class SmeltingTools_EPOCH {price = 500;};
	class ItemCampingLight {price = 250;};
	class ItemSeedBag {price = 100;};
	class KitCinderTower {price = 2500;};
	
	// Radios
	class EpochRadio0 {price = 2;};
	class EpochRadio1 {price = 4;};
	class EpochRadio2 {price = 6;};
	class EpochRadio3 {price = 8;};
	class EpochRadio4 {price = 10;};
	class EpochRadio5 {price = 12;};
	class EpochRadio6 {price = 14;};
	class EpochRadio7 {price = 16;};
	class EpochRadio8 {price = 18;};
	class EpochRadio9 {price = 20;};

	class VehicleRepair {price = 35;};
	class VehicleRepairLg {price = 50;};

	class WhiskeyNoodle {price = 80;};

	class ItemWatch {price = 2;};

	class Binocular {price = 4;};
	class NVG_EPOCH {price = 35;};
	class acc_flashlight {price = 4;};
	class acc_pointer_IR {price = 5;};

	class srifle_EBR_F {price = 150;};
	class srifle_GM6_F {price = 150;};
	class srifle_LRR_F {price = 200;};
	class srifle_DMR_01_F {price = 200;};

	class 20Rnd_762x51_Mag {price = 4;};
	class 5Rnd_127x108_Mag {price = 3; tax = 0.9;};
	class 5Rnd_127x108_APDS_Mag {price = 6; tax = 0.9;};
	class 7Rnd_408_Mag {price = 4; tax = 0.9;};

	class 10Rnd_762x51_Mag {price = 2; tax = 0.9;};

	// Paint
	class PaintCanClear {price = 1;};
	class PaintCanBlk {price = 1;};
	class PaintCanBlu {price = 1;};
	class PaintCanBrn {price = 1;};
	class PaintCanGrn {price = 1;};
	class PaintCanOra {price = 1;};
	class PaintCanPur {price = 1;};
	class PaintCanRed {price = 1;};
	class PaintCanTeal {price = 1;};
	class PaintCanYel {price = 1;};

	class ItemDocument {price = 5;};
	class ItemDocumentMission {price = 5;};
	class ItemMixOil {price = 5;};
	class emptyjar_epoch {price = 5;};
	class jerrycan_epoch { price = 10; };
	class speargun_epoch { price = 75; };
	class spear_magazine { price = 5; tax = 0.9; };
	class lighter_epoch { price = 50; };
	class WoodLog_EPOCH { price = 1; };
	class ItemRope { price = 5; };
	class ItemStick { price = 1; };
	class ItemRock { price = 1; };

	// Food
	class FoodBioMeat {price = 1;};
	class FoodMeeps {price = 50;};
	class FoodSnooter {price = 5;};
	class sardines_epoch {price = 2;};
	class meatballs_epoch {price = 2;};
	class scam_epoch {price = 1;};
	class sweetcorn_epoch {price = 2;};
	class CookedSheep_EPOCH {price = 5;};
	class CookedGoat_EPOCH {price = 5;};
	class SnakeMeat_EPOCH {price = 3;};
	class CookedRabbit_EPOCH {price = 5;};
	class CookedChicken_EPOCH {price = 3;};
	class ItemTrout {price = 1;};
	class ItemSeaBass {price = 5;};
	class ItemTuna {price = 10;};

	// Drinks
	class FoodWalkNSons {price = 5;};
	class ItemSodaOrangeSherbet {price = 4;};
	class ItemSodaPurple {price = 5;};
	class ItemSodaMocha {price = 8;};
	class ItemSodaBurst {price = 4;};
	class ItemSodaRbull {price = 5;};

	// Medical
	class FAK {price = 3;};
	class Towelette {price = 1;};
	class HeatPack {price = 2;};
	class ColdPack {price = 2;};
	
	class sr25_epoch { price = 50; };
	class l85a2_epoch { price = 50; };
	class l85a2_pink_epoch { price = 50; };
	class l85a2_ugl_epoch { price = 50; };
	class arifle_Katiba_F {price = 50;};
	class arifle_Katiba_C_F {price = 50;};
	class arifle_Katiba_GL_F {price = 75;};
	class arifle_MXC_F {price = 50;};
	class arifle_MX_F {price = 50;};
	class arifle_MX_GL_F {price = 75;};
	class arifle_MXM_F {price = 50;};
	class arifle_SDAR_F {price = 50;};
	class arifle_TRG21_F {price = 50;};
	class arifle_TRG20_F {price = 50;};
	class arifle_TRG21_GL_F {price = 75;};
	class arifle_Mk20_F {price = 50;};
	class arifle_Mk20C_F {price = 50;};
	class arifle_Mk20_GL_F {price = 75;};
	class arifle_Mk20_plain_F {price = 50;};
	class arifle_Mk20C_plain_F {price = 50;};
	class arifle_Mk20_GL_plain_F {price = 75;};
	class SMG_01_F {price = 35;};
	class SMG_02_F {price = 35;};
	class hgun_PDW2000_F {price = 35;};
	class arifle_MXM_Black_F {price = 50;};
	class arifle_MX_GL_Black_F {price = 75;};
	class arifle_MX_Black_F {price = 50;};
	class arifle_MXC_Black_F {price = 50;};
	class Rollins_F {price = 50;};

	class 30Rnd_65x39_caseless_green {price = 3; tax = 0.9;};
	class 30Rnd_65x39_caseless_green_mag_Tracer {price = 4; tax = 0.9;};
	class 30Rnd_65x39_caseless_mag {price = 3; tax = 0.9;};
	class 30Rnd_65x39_caseless_mag_Tracer {price = 4; tax = 0.9;};
	class 20Rnd_556x45_UW_mag {price = 3; tax = 0.9;};
	class 30Rnd_556x45_Stanag {price = 3; tax = 0.9;};
	class 30Rnd_556x45_Stanag_Tracer_Red {price = 4; tax = 0.9;};
	class 30Rnd_556x45_Stanag_Tracer_Green {price = 4; tax = 0.9;};
	class 30Rnd_556x45_Stanag_Tracer_Yellow {price = 4; tax = 0.9;};
	class 30Rnd_45ACP_Mag_SMG_01 {price = 2; tax = 0.9;};
	class 30Rnd_45ACP_Mag_SMG_01_Tracer_Green {price = 3; tax = 0.9;};
	class 5Rnd_rollins_mag {price = 2; tax = 0.9;};

	class UGL_FlareWhite_F {price = 2;};
	class UGL_FlareGreen_F {price = 2;};
	class UGL_FlareRed_F {price = 2;};
	class UGL_FlareYellow_F {price = 2;};
	class UGL_FlareCIR_F {price = 2;};
	class 1Rnd_Smoke_Grenade_shell {price = 4;};
	class 1Rnd_SmokeRed_Grenade_shell {price = 4;};
	class 1Rnd_SmokeGreen_Grenade_shell {price = 4;};
	class 1Rnd_SmokeYellow_Grenade_shell {price = 4;};
	class 1Rnd_SmokePurple_Grenade_shell {price = 4;};
	class 1Rnd_SmokeBlue_Grenade_shell {price = 4;};
	class 1Rnd_SmokeOrange_Grenade_shell {price = 4;};
	class 3Rnd_HE_Grenade_shell {price = 10;};
	class 3Rnd_UGL_FlareWhite_F {price = 4;};
	class 3Rnd_UGL_FlareGreen_F {price = 4;};
	class 3Rnd_UGL_FlareRed_F {price = 4;};
	class 3Rnd_UGL_FlareYellow_F {price = 4;};
	class 3Rnd_UGL_FlareCIR_F {price = 4;};
	class 3Rnd_Smoke_Grenade_shell {price = 3;};
	class 3Rnd_SmokeRed_Grenade_shell {price = 3;};
	class 3Rnd_SmokeGreen_Grenade_shell {price = 3;};
	class 3Rnd_SmokeYellow_Grenade_shell {price = 3;};
	class 3Rnd_SmokePurple_Grenade_shell {price = 3;};
	class 3Rnd_SmokeBlue_Grenade_shell {price = 3;};
	class 3Rnd_SmokeOrange_Grenade_shell {price = 3;};

	class LMG_Mk200_F {price = 150;};
	class arifle_MX_SW_F {price = 150;};
	class LMG_Zafir_F {price = 150;};
	class arifle_MX_SW_Black_F {price = 150;};

	// new weapons
	class m249_EPOCH {price = 150;};
	class m249Tan_EPOCH {price = 150;};
	class m107Tan_EPOCH {price = 200;};
	class m107_EPOCH {price = 200;};
	class m16_EPOCH {price = 100;};
	class m16Red_EPOCH {price = 125;};
	class M14_EPOCH {price = 125;};
	class M14Grn_EPOCH {price = 150;};
	class m4a3_EPOCH {price = 100;};
	class AKM_EPOCH {price = 100;};
	
	// mas weapons
	class srifle_mas_m107_d_sd {price = 200;};
	class srifle_mas_m107_d {price = 200;};
	class arifle_mas_mk17 {price = 180;};
	class LMG_mas_M240_F {price = 180;};
	class LMG_mas_M240_F_a {price = 180;};
	class LMG_mas_mg3_F {price = 180;};
	class LMG_mas_mg3_F_h {price = 180;};
	class arifle_mas_mk17_gl_e {price = 180;};
	class LMG_mas_Mk48_F {price = 80;};
	class LMG_mas_M60_F {price = 80;};
	class LMG_mas_M60_F_a {price = 80;};
	class arifle_mas_hk417c {price = 80;};
	class arifle_mas_g36c {price = 80;};
	class arifle_mas_mk16 {price = 80;};
	class arifle_mas_arx_l {price = 80;};
	class arifle_mas_arx {price = 80;};
	class arifle_mas_g3 {price = 80;};
	class arifle_mas_fal {price = 80;};
	class arifle_mas_lee_l {price = 80;};
	class arifle_mas_m1014 {price = 60;};
	class srifle_mas_lrr {price = 200;};
	class hgun_mas_mp7_F {price = 40;};
	class hgun_mas_mp7p_F {price = 40;};
	class arifle_mas_bizon {price = 40;};
	class arifle_mas_m70 {price = 80;};
	class srifle_mas_m91 {price = 180;};
	class srifle_mas_svd {price = 170;};
	class arifle_mas_asval {price = 80;};
	class srifle_mas_ksvk {price = 200;};
	class LMG_mas_rpk_F_a {price = 80;};
	class LMG_mas_pkm_F {price = 180;};
	
	// mas magazines
	class 20Rnd_mas_762x51_Stanag {price = 8;};
	class 20Rnd_mas_762x51_T_Stanag {price = 8;};
	class 30Rnd_mas_556x45_T_Stanag {price = 5;};
	class 100Rnd_mas_762x51_Stanag {price = 10;};
	class 100Rnd_mas_762x51_T_Stanag {price = 10;};
	class 5Rnd_mas_762x51_Stanag {price = 5;};
	class 30Rnd_mas_556x45_Stanag {price = 5;};
	class 7Rnd_mas_12Gauge_Slug {price = 4;};
	class 7Rnd_mas_12Gauge_Pellets {price = 4;};
	class 5Rnd_mas_127x99_dem_Stanag {price = 30;};
	class 5Rnd_mas_127x99_T_Stanag {price = 15;};
	class 5Rnd_mas_127x99_Stanag {price = 15;};
	class 10Rnd_mas_338_Stanag {price = 15;};
	class 40Rnd_mas_46x30_Mag {price = 4;};
	class 64Rnd_mas_9x18_mag {price = 4;};
	class 30Rnd_mas_762x39_mag {price = 8;};
	class 10Rnd_mas_762x54_mag {price = 8;};
	class 10Rnd_mas_762x54_T_mag {price = 8;};
	class 30Rnd_mas_9x39_mag {price = 4;};
	class 5Rnd_mas_127x108_dem_mag {price = 15;};
	class 5Rnd_mas_127x108_mag {price = 15;};
	class 100Rnd_mas_545x39_mag {price = 10;};
	class 100Rnd_mas_762x54_mag {price = 10;};
	class 100Rnd_mas_762x54_T_mag {price = 10;};
	
	// mas backpacks
	class B_BergenG {price = 8;};
	
	// new magazines kiory
	class 30rnd_556_magazine{ price = 5; tax = 0.9; };
	class 20rnd_762_magazine{ price = 5; tax = 0.9; };
	// new magazines seq
	class 30Rnd_762x39_Mag {price = 5; tax = 0.9;};
	class 200Rnd_556x45_M249 {price = 5; tax = 0.9;};

	class 200Rnd_65x39_cased_Box {price = 5; tax = 0.9;};
	class 100Rnd_65x39_caseless_mag {price = 3; tax = 0.9;};
	class 200Rnd_65x39_cased_Box_Tracer {price = 5; tax = 0.9;};
	class 100Rnd_65x39_caseless_mag_Tracer {price = 4; tax = 0.9;};
	class 150Rnd_762x51_Box {price = 4; tax = 0.9;};
	class 150Rnd_762x51_Box_Tracer {price = 5; tax = 0.9;};

	class Rangefinder {price = 4;};
	class Laserdesignator {price = 4;};
	class hgun_ACPC2_F {price = 5;};
	class hgun_Rook40_F {price = 5;};
	class hgun_P07_F {price = 5;};
	class hgun_Pistol_heavy_01_F {price = 7;};
	class hgun_Pistol_heavy_02_F {price = 10;};
	class ruger_pistol_epoch {price = 4;};
	class 1911_pistol_epoch {price = 6;};
	class hgun_Pistol_Signal_F {price = 4;};
	class Hatchet {price = 25;};
	class MultiGun {price = 100;};
	class MeleeSledge {price = 50;};

	class CrudeHatchet { price = 5; };
	class MeleeMaul { price = 10; };
	class WoodClub { price = 5; };
	class Plunger { price = 15; };
	
	class 16Rnd_9x21_Mag {price = 2; tax = 0.9;};
	class 30Rnd_9x21_Mag {price = 3; tax = 0.9;};
	class 9Rnd_45ACP_Mag {price = 1; tax = 0.9;};
	class 11Rnd_45ACP_Mag {price = 1; tax = 0.9;};
	class 6Rnd_45ACP_Cylinder {price = 1; tax = 0.9;};
	class 10rnd_22X44_magazine {price = 2; tax = 0.9;};
	class 9rnd_45X88_magazine {price = 2; tax = 0.9;};
	class 6Rnd_GreenSignal_F {price = 1;};
	class 6Rnd_RedSignal_F {price = 1; tax = 0.9;};
	class EnergyPack {price = 3; tax = 0.9;};
	class EnergyPackLg {price = 30; tax = 0.9;};

	class optic_Arco {price = 3;};
	class optic_Hamr {price = 3;};
	class optic_Aco {price = 2;};
	class optic_ACO_grn {price = 3;};
	class optic_Aco_smg {price = 2;};
	class optic_ACO_grn_smg {price = 3;};
	class optic_Holosight {price = 2;};
	class optic_Holosight_smg {price = 2;};
	class optic_SOS {price = 3;};
	class optic_MRCO {price = 3;};
	class optic_DMS {price = 3;};
	class optic_Yorris {price = 2;};
	class optic_MRD {price = 1;};
	class optic_LRPS {price = 3;};
	class optic_NVS {price = 7;};
	class optic_Nightstalker {price = 10;};
	class optic_tws {price = 5;};
	class optic_tws_mg {price = 5;};
	class Elcan_epoch { price = 5; };
	class Elcan_reflex_epoch { price = 10; };

	class muzzle_snds_H {price = 2;};
	class muzzle_snds_L {price = 2;};
	class muzzle_snds_M {price = 2;};
	class muzzle_snds_B {price = 2;};
	class muzzle_snds_H_MG {price = 2;};
	class muzzle_snds_acp {price = 2;};
	class Heal_EPOCH {price = 3;};
	class Defib_EPOCH {price = 5;};
	class Repair_EPOCH {price = 2;};
	class muzzle_sr25S_epoch { price = 2; };

	class PartOreGold {price = 70;};
	class PartOreSilver {price = 7;};
	class PartOre {price = 1;};
	class ItemGoldBar {price = 100;};
	class ItemSilverBar {price = 10;};
	class ItemGoldBar10oz {price = 1000;};
	class ItemTopaz {price = 25;};
	class ItemOnyx {price = 30;};
	class ItemSapphire {price = 50;};
	class ItemAmethyst {price = 25;};
	class ItemEmerald {price = 25;};
	class ItemCitrine {price = 25;};
	class ItemRuby {price = 75;};
	class ItemQuartz {price = 5;};
	class ItemJade {price = 100;};
	class ItemGarnet {price = 25;};
	class ItemKiloHemp {price = 100;};

	// Building resources
	class PartPlankPack {price = 2;};
	class CinderBlocks {price = 20;};
	class MortarBucket {price = 20;};
	class ItemScraps {price = 5;};
	class ItemCorrugated {price = 25;};
	class ItemCorrugatedLg {price = 75;};

	// Building parts
	class KitStudWall {price = 10;};
	class KitWoodFloor {price = 10;};
	class KitWoodStairs {price = 10;};
	class KitWoodRamp {price = 14;};
	class KitFirePlace {price = 4;};
	class KitTiPi {price = 10;};
	class KitShelf {price = 90;};
	class KitWoodFoundation { price = 20; };
	class KitFoundation {price = 90;};
	class KitPlotPole {price = 300;};
	class KitCinderWall {price = 140;};

	class honey_epoch {price = 5;};
	class Pelt_EPOCH {price = 1;};
	class Venom_EPOCH {price = 10;};

	class HandGrenade_Stone {price = 1;};
	class SmokeShell {price = 2;};
	class SmokeShellYellow {price = 2;};
	class SmokeShellGreen {price = 2;};
	class SmokeShellRed {price = 2;};
	class SmokeShellPurple {price = 2;};
	class SmokeShellOrange {price = 2;};
	class SmokeShellBlue {price = 2;};
	class Chemlight_green {price = 1;};
	class Chemlight_red {price = 1;};
	class Chemlight_yellow {price = 1;};
	class Chemlight_blue {price = 1;};

	class HandGrenade {price = 15;};
	class MiniGrenade {price = 10;};
	class DemoCharge_Remote_Mag {price = 40;};
	class SatchelCharge_Remote_Mag {price = 75;};
	class ATMine_Range_Mag {price = 50;};
	class ClaymoreDirectionalMine_Remote_Mag {price = 50;};
	class APERSMine_Range_Mag {price = 30;};
	class APERSBoundingMine_Range_Mag {price = 50;};
	class SLAMDirectionalMine_Wire_Mag {price = 40;};
	class APERSTripMine_Wire_Mag {price = 30;};


	class B_AssaultPack_cbr {price = 10;};
	class B_AssaultPack_dgtl {price = 10;};
	class B_AssaultPack_khk {price = 10;};
	class B_AssaultPack_mcamo {price = 10;};
	class B_AssaultPack_ocamo {price = 10;};
	class B_AssaultPack_rgr {price = 10;};
	class B_AssaultPack_sgg {price = 10;};
	class B_Carryall_cbr {price = 1;};
	class B_Carryall_khk {price = 10;};
	class B_Carryall_mcamo {price = 10;};
	class B_Carryall_ocamo {price = 10;};
	class B_Carryall_oli {price = 10;};
	class B_Carryall_oucamo {price = 10;};
	class B_FieldPack_blk {price = 10;};
	class B_FieldPack_cbr {price = 10;};
	class B_FieldPack_khk {price = 10;};
	class B_FieldPack_ocamo {price = 10;};
	class B_FieldPack_oli {price = 10;};
	class B_FieldPack_oucamo {price = 10;};
	class B_Kitbag_cbr {price = 10;};
	class B_Kitbag_mcamo {price = 10;};
	class B_Kitbag_rgr {price = 10;};
	class B_Kitbag_sgg {price = 10;};
	class B_Parachute {price = 15;};
	class B_TacticalPack_blk {price = 10;};
	class B_TacticalPack_mcamo {price = 10;};
	class B_TacticalPack_ocamo {price = 10;};
	class B_TacticalPack_oli {price = 10;};
	class B_TacticalPack_rgr {price = 10;};
	class smallbackpack_red_epoch {price = 10;};
	class smallbackpack_green_epoch {price = 10;};
	class smallbackpack_teal_epoch {price = 10;};
	class smallbackpack_pink_epoch {price = 10;};

	class U_O_CombatUniform_ocamo {price = 5;};
	class U_O_GhillieSuit {price = 5;};
	class U_O_PilotCoveralls {price = 5;};
	class U_O_Wetsuit {price = 5;};
	class U_OG_Guerilla1_1 {price = 5;};
	class U_OG_Guerilla2_1 {price = 5;};
	class U_OG_Guerilla2_2 {price = 5;};
	class U_OG_Guerilla2_3 {price = 5;};
	class U_OG_Guerilla3_1 {price = 5;};
	class U_OG_Guerilla3_2 {price = 5;};
	class U_OG_leader {price = 5;};

	class U_C_Poloshirt_stripped {price = 4;};
	class U_C_Poloshirt_blue {price = 4;};
	class U_C_Poloshirt_burgundy {price = 4;};
	class U_C_Poloshirt_tricolour {price = 4;};
	class U_C_Poloshirt_salmon {price = 4;};
	class U_C_Poloshirt_redwhite {price = 4;};
	class U_C_Poor_1 {price = 5;};
	class U_C_WorkerCoveralls {price = 5;};
	class U_C_Journalist {price = 5;};
	class U_C_Scientist {price = 5;};
	class U_OrestesBody {price = 5;};
	class U_Wetsuit_uniform {price = 5;};
	class U_Wetsuit_White {price = 5;};
	class U_Wetsuit_Blue {price = 5;};
	class U_Wetsuit_Purp {price = 5;};
	class U_Wetsuit_Camo {price = 5;};
	class U_Camo_uniform {price = 5;};
	class U_ghillie1_uniform {price = 5;};
	class U_ghillie2_uniform {price = 5;};
	class U_ghillie3_uniform {price = 5;};
	class U_CamoBlue_uniform {price = 5;};
	class U_CamoBrn_uniform {price = 5;};
	class U_CamoRed_uniform {price = 5;};

	class U_C_Driver_1 {price = 5;};
	class U_C_Driver_2 {price = 5;};
	class U_C_Driver_3 {price = 5;};
	class U_C_Driver_4 {price = 5;};
	class U_C_Driver_1_black {price = 5;};
	class U_C_Driver_1_blue {price = 5;};
	class U_C_Driver_1_green {price = 5;};
	class U_C_Driver_1_red {price = 5;};
	class U_C_Driver_1_white {price = 5;};
	class U_C_Driver_1_yellow {price = 5;};
	class U_C_Driver_1_orange {price = 5;};

	class V_1_EPOCH {price = 5;};
	class V_2_EPOCH {price = 5;};
	class V_3_EPOCH {price = 5;};
	class V_4_EPOCH {price = 5;};
	class V_5_EPOCH {price = 5;};
	class V_6_EPOCH {price = 5;};
	class V_7_EPOCH {price = 5;};
	class V_8_EPOCH {price = 5;};
	class V_9_EPOCH {price = 5;};
	class V_10_EPOCH {price = 5;};
	class V_11_EPOCH {price = 5;};
	class V_12_EPOCH {price = 5;};
	class V_13_EPOCH {price = 5;};
	class V_14_EPOCH {price = 5;};
	class V_15_EPOCH {price = 5;};
	class V_16_EPOCH {price = 5;};
	class V_17_EPOCH {price = 5;};
	class V_18_EPOCH {price = 5;};
	class V_19_EPOCH {price = 5;};
	class V_20_EPOCH {price = 5;};
	class V_21_EPOCH {price = 5;};
	class V_22_EPOCH {price = 5;};
	class V_23_EPOCH {price = 5;};
	class V_24_EPOCH {price = 5;};
	class V_25_EPOCH {price = 5;};
	class V_26_EPOCH {price = 5;};
	class V_27_EPOCH {price = 5;};
	class V_28_EPOCH {price = 5;};
	class V_29_EPOCH {price = 5;};
	class V_30_EPOCH {price = 5;};
	class V_31_EPOCH {price = 5;};
	class V_32_EPOCH {price = 5;};
	class V_33_EPOCH {price = 5;};
	class V_34_EPOCH {price = 5;};
	class V_35_EPOCH {price = 5;};
	class V_36_EPOCH {price = 5;};
	class V_37_EPOCH {price = 5;};
	class V_38_EPOCH {price = 5;};
	class V_39_EPOCH {price = 5;};
	class V_40_EPOCH {price = 5;};

	class H_1_EPOCH {price = 3;};
	class H_2_EPOCH {price = 3;};
	class H_3_EPOCH {price = 3;};
	class H_4_EPOCH {price = 3;};
	class H_5_EPOCH {price = 3;};
	class H_6_EPOCH {price = 3;};
	class H_7_EPOCH {price = 3;};
	class H_8_EPOCH {price = 3;};
	class H_9_EPOCH {price = 3;};
	class H_10_EPOCH {price = 3;};
	class H_11_EPOCH {price = 3;};
	class H_12_EPOCH {price = 3;};
	class H_13_EPOCH {price = 3;};
	class H_14_EPOCH {price = 3;};
	class H_15_EPOCH {price = 3;};
	class H_16_EPOCH {price = 3;};
	class H_17_EPOCH {price = 3;};
	class H_18_EPOCH {price = 3;};
	class H_19_EPOCH {price = 3;};
	class H_20_EPOCH {price = 3;};
	class H_21_EPOCH {price = 3;};
	class H_22_EPOCH {price = 3;};
	class H_23_EPOCH {price = 3;};
	class H_24_EPOCH {price = 3;};
	class H_25_EPOCH {price = 3;};
	class H_26_EPOCH {price = 3;};
	class H_27_EPOCH {price = 3;};
	class H_28_EPOCH {price = 3;};
	class H_29_EPOCH {price = 3;};
	class H_30_EPOCH {price = 3;};
	class H_31_EPOCH {price = 3;};
	class H_32_EPOCH {price = 3;};
	class H_33_EPOCH {price = 3;};
	class H_34_EPOCH {price = 3;};
	class H_35_EPOCH {price = 3;};
	class H_36_EPOCH {price = 3;};
	class H_37_EPOCH {price = 3;};
	class H_38_EPOCH {price = 3;};
	class H_39_EPOCH {price = 3;};
	class H_40_EPOCH {price = 3;};
	class H_41_EPOCH {price = 3;};
	class H_42_EPOCH {price = 3;};
	class H_43_EPOCH {price = 3;};
	class H_44_EPOCH {price = 3;};
	class H_45_EPOCH {price = 3;};
	class H_46_EPOCH {price = 3;};
	class H_47_EPOCH {price = 3;};
	class H_48_EPOCH {price = 3;};
	class H_49_EPOCH {price = 3;};
	class H_50_EPOCH {price = 3;};
	class H_51_EPOCH {price = 3;};
	class H_52_EPOCH {price = 3;};
	class H_53_EPOCH {price = 3;};
	class H_54_EPOCH {price = 3;};
	class H_55_EPOCH {price = 3;};
	class H_56_EPOCH {price = 3;};
	class H_57_EPOCH {price = 3;};
	class H_58_EPOCH {price = 3;};
	class H_59_EPOCH {price = 3;};
	class H_60_EPOCH {price = 3;};
	class H_61_EPOCH {price = 3;};
	class H_62_EPOCH {price = 3;};
	class H_63_EPOCH {price = 3;};
	class H_64_EPOCH {price = 3;};
	class H_65_EPOCH {price = 3;};
	class H_66_EPOCH {price = 3;};
	class H_67_EPOCH {price = 3;};
	class H_68_EPOCH {price = 3;};
	class H_69_EPOCH {price = 3;};
	class H_70_EPOCH {price = 3;};
	class H_71_EPOCH {price = 3;};
	class H_72_EPOCH {price = 3;};
	class H_73_EPOCH {price = 3;};
	class H_74_EPOCH {price = 3;};
	class H_75_EPOCH {price = 3;};
	class H_76_EPOCH {price = 3;};
	class H_77_EPOCH {price = 3;};
	class H_78_EPOCH {price = 3;};
	class H_79_EPOCH {price = 3;};
	class H_80_EPOCH {price = 3;};
	class H_81_EPOCH {price = 3;};
	class H_82_EPOCH {price = 3;};
	class H_83_EPOCH {price = 3;};
	class H_84_EPOCH {price = 3;};
	class H_85_EPOCH {price = 3;};
	class H_86_EPOCH {price = 3;};
	class H_87_EPOCH {price = 3;};
	class H_88_EPOCH {price = 3;};
	class H_89_EPOCH {price = 3;};
	class H_90_EPOCH {price = 3;};
	class H_91_EPOCH {price = 3;};
	class H_92_EPOCH {price = 3;};
	class H_93_EPOCH {price = 3;};
	class H_94_EPOCH {price = 5;};
	class H_95_EPOCH {price = 5;};
	class H_96_EPOCH {price = 5;};
	class H_97_EPOCH {price = 5;};
	class H_98_EPOCH {price = 5;};
	class H_99_EPOCH {price = 5;};
	class H_100_EPOCH {price = 5;};
	class H_101_EPOCH {price = 5;};
	class H_102_EPOCH {price = 5;};
	class H_103_EPOCH {price = 5;};
	class H_104_EPOCH {price = 3;};
	class wolf_mask_epoch {price = 30;};
	class pkin_mask_epoch {price = 30;};

	class C_Offroad_01_EPOCH {price = 750;};
	class C_Quadbike_01_EPOCH {price = 500;};
	class C_Hatchback_01_EPOCH {price = 750;};
	class C_Hatchback_02_EPOCH {price = 1000;};
	class C_SUV_01_EPOCH {price = 750;};
	class C_Rubberboat_EPOCH {price = 500;};
	class C_Rubberboat_02_EPOCH {price = 500;};
	class C_Rubberboat_03_EPOCH {price = 500;};
	class C_Rubberboat_04_EPOCH {price = 500;};
	class C_Van_01_box_EPOCH {price = 1000;};
	class C_Van_01_transport_EPOCH {price = 1000;};
	class C_Boat_Civil_01_EPOCH {price = 750;};
	class C_Boat_Civil_01_police_EPOCH {price = 750;};
	class C_Boat_Civil_01_rescue_EPOCH {price = 750;};
	class B_Heli_Light_01_EPOCH {price = 2500;};
	class B_SDV_01_EPOCH {price = 1000;};
	class B_MRAP_01_EPOCH {price = 2500;};
	class B_G_Offroad_01_armed_EPOCH {price = 2500;};
	class B_Truck_01_transport_EPOCH {price = 1000;};
	class B_Truck_01_covered_EPOCH {price = 1000;};
	class B_Truck_01_mover_EPOCH {price = 1000;};
	class B_Truck_01_box_EPOCH {price = 1000;};
	class O_Truck_02_covered_EPOCH {price = 1000;};
	class O_Truck_02_transport_EPOCH {price = 1000;};
	class O_Truck_03_covered_EPOCH {price = 1000;};
	class O_Truck_02_box_EPOCH {price = 1000;};
	class O_Heli_Light_02_unarmed_EPOCH {price = 2500;};
	class I_Heli_Transport_02_EPOCH {price = 2500;};
	class I_Heli_light_03_unarmed_EPOCH {price = 2500;};

	class O_Heli_Transport_04_EPOCH {price = 2500;};
	class O_Heli_Transport_04_bench_EPOCH {price = 2500;};
	class O_Heli_Transport_04_box_EPOCH {price = 2500;};
	class O_Heli_Transport_04_covered_EPOCH {price = 2500;};
	class B_Heli_Transport_03_unarmed_EPOCH {price = 2500;};

	class jetski_epoch {price = 500;};
	class ebike_epoch {price = 1000;};
	class mosquito_epoch { price = 1500; };
	class K01 {price = 300;};
	class K02 {price = 300;};
	class K03 {price = 300;};
	class K04 {price = 300;};
	
	//mas vehicles
	class B_mas_cars_Hilux_Unarmed {price = 1000;};
	class B_mas_cars_Hilux_Med {price = 1000;};
	class I_mas_cars_UAZ_Unarmed {price = 1000;};
	class I_mas_cars_UAZ_Med {price = 1000;};
	class I_mas_cars_UAZ_MG {price = 2000;};
	class B_mas_cars_LR_Unarmed {price = 1000;};
	class B_mas_cars_LR_Med {price = 1000;};
	class B_mas_CH_47F {price = 3000;};
	class B_mas_UH1Y_UNA_F {price = 2500;};
	class B_mas_UH1Y_MEV_F {price = 2500;};
	class B_mas_UH1Y_F {price = 3000;};
	class B_mas_cars_Hilux_MG {price = 2000;};
	class B_mas_HMMWV_UNA {price = 2500;};
	class B_mas_HMMWV_MEV {price = 2500;};
	class B_mas_HMMWV_SOV_M134 {price = 3000;};
	class B_mas_HMMWV_M134 {price = 3000;};
	class B_mas_UH60M {price = 3000;};
	class B_mas_UH60M_MEV {price = 2500;};
	class B_mas_UH60M_SF {price = 2500;};
	
	//Mission Items
	class B_UavTerminal {price = 10;};
	class O_UavTerminal {price = 10;};
};
/*[[[end]]]*/